### ISSUE TITLE
Tasten am Schalter funktionieren nicht

### ISSUE THREAD

**Issue by Terabyte2000** [wiresio/CCU2#1]
Hallo

Leider funktionieren die Tasten am Schalter damit nicht. Ist das normal?
In der CCU kann ich das Licht aber ein und ausschalten.

**Comment by wiresio** [comment]
Funktionieren die Taster “stand-alone” also ohne CCU2? Zur Programmierung der Taster empfehle ich ohnehin FHEM. Dieser Patch dient dazu, den Schalter mit der Custom Firmware an der CCU2 verfügbar zu machen um bspw. die CCU Programme zu benutzen.

**Comment by Terabyte2000** [comment]
Wie meinst du das mit dem programmieren über fhem?
Wenn ich im fhem etwas einstelle dann wird das ja nicht in die CCU2 mitübernommen nehme ich an oder bleibt diese Einstellung dann im Schalter?

**Comment by wiresio** [comment]
Genau, die Einstellungen bleiben im Schalter. Schau mal in mein FHEM Repo - da ist ein Link zu einem Thread wo das diskutiert wird.

**Comment by Terabyte2000** [comment]
Danke. Werde ich testen.

Funktionieren bei dir die Schalter ohne Probleme in der CCU2?
Ich bekomme nämlich auch immer wenn ich auf den Channel 1 oder 2 zugreife eine Fehlermeldung, dass die Verbindung gestört ist.

**Comment by wiresio** [comment]
Die Fehlermeldung kommt bei mir auch. Schalter funktionieren aber.
